name: silaturker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^5.5.2
  animated_background: ^1.0.5
  chewie: ^1.2.2
  font_awesome_flutter: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/silaaa.jpg
    - assets/hi.gif

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: fonts\RobotoMono-Regular.ttf
        - asset: fonts\RobotoMono-Light.ttf
          weight: 300
        - asset: fonts\RobotoMono-Thin.ttf
          weight: 100
    - family: Raleway
      fonts:
        - asset: fonts\Raleway-Bold.ttf
          weight: 700
        - asset: fonts\Raleway-Italic.ttf
          style: italic
        - asset: fonts\Raleway-Light.ttf
        - asset: fonts\Raleway-Regular.ttf